repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Supprime les espaces inutiles en fin de ligne
      - id: trailing-whitespace
        exclude: ^(env|\.venv|\.direnv|site-packages|node_modules|\.*\.yaml)/

      # Garantit la présence d’un saut de ligne en fin de fichier
      - id: end-of-file-fixer
        exclude: ^(env|\.venv|\.direnv|site-packages|node_modules|\.*\.yaml)/

  # Ruff : linter Python moderne, rapide et consolidé
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      # Détection d’erreurs, mauvaises pratiques et incohérences Python
      - id: ruff

  # Bandit : analyse de sécurité statique pour Python
  # Détection de patterns de code potentiellement dangereux
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit

  # Gitleaks : prévention des fuites de secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.17.0
    hooks:
      - id: gitleaks
        # detect : lance l’analyse
        # -v : mode verbeux pour une meilleure traçabilité
        args: [ "detect", "-v" ]
