name: deploy mkdocs
on: [push, pull_request]
permissions:
  contents: write
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: mkdocs build
#      - run: mkdocs gh-deploy --force
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './site/'
      - uses: actions/deploy-pages@v4
